# Generated by Django 4.2.6 on 2024-12-15 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filename',
            name='filename',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_channel_messages', to='app_telegram_client.getpostchannel'),
        ),
    ]
