# Generated by Django 4.2.6 on 2024-12-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram_client', '0003_remove_filename_message_filename_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filename',
            name='message_id',
            field=models.CharField(max_length=100),
        ),
    ]
