# Generated by Django 4.2.6 on 2024-12-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram_client', '0006_postchannel_sign_alter_message_history_from_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postchannel',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_telegram_client.channel_type'),
            preserve_default=False,
        ),
    ]
